name: deploy
on: 
    pull_request:
      types: 
          - closed
      branches:    
      - '[0-9]+[0-9]+[0-9]+[0-9].x'
jobs:
  check-test-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: echo hamza     
      
      
